name: Bug report
description: If you find something that does not work the way it should
labels: [ "to-evaluate" ]
body:
  - type: checkboxes
    id: pre-check
    attributes:
      label: Search before asking
      description: "Please search [issues](https://github.com/FasterXML/jackson-databind/issues) to check if your issue has already been reported."
      options:
        - label: "I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar."
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: Version Information
      description: "Which Jackson version(s) was this for?"
      placeholder: |
        ex) 2.15.2 
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
      description: "If you have a way to reproduce this with:"
      value: |
        <-- Any of the following
        1. Brief code sample/snippet: include here in preformatted/code section
        2. Longer example stored somewhere else (diff repo, snippet), add a link
        3. Textual explanation: include here
         -->
        ```java
        // Your code here
        ``` 
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: "If reproduction itself needs further explanation, you may also add more details here."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
  - type: markdown
    attributes:
      value: "Thanks for reporting the bug!"
