name: Documentation request
description: If you have a great idea of how to improve documentation
labels: [ "to-evaluate" ]
body:
  - type: textarea
    id: documentation-improvement
    attributes:
      label: Documentation Improvement
      description: "Which part of documentation is missing, incorrect, or out of date? Please describe. You may suggest changes, deletions, additions."
    validations:
      required: true
