name: CIFuzz
on:
  pull_request:
    branches:
    - "2.18"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@3d9cfb650abdeb4893f8aa8f4e6f25d63752601d # master
      with:
        oss-fuzz-project-name: 'jackson-databind'
        dry-run: false
        language: jvm
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@3d9cfb650abdeb4893f8aa8f4e6f25d63752601d # master
      with:
        oss-fuzz-project-name: 'jackson-databind'
        fuzz-seconds: 1200
        dry-run: false
        language: jvm
    - name: Upload Crash
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
