name: Re-build on jackson-core v3 push
on:
  repository_dispatch:
    types: [jackson-core-pushed-v3]
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Do we want wide matrix build? For now, limited
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '17', '21']
        os: ['ubuntu-22.04']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: master
    - name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build and test
      run: ./mvnw -B -ff -ntp verify

  # And let's proceed recursively...
  trigger-dep-build:
    name: Trigger downstream builds
    needs: [build]
    uses: ./.github/workflows/trigger_dep_builds_v3.yml
    secrets:
      token: ${{ secrets.REPO_DISPATCH }}
