name: Trigger downstream builds
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  trigger-dep-build:
    name: Trigger downstream builds
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      # Won't matter a lot but try to make dispatching non-parallel
      max-parallel: 1
      matrix:
        repo:
          - 'FasterXML/jackson-modules-base'
          - 'FasterXML/jackson-dataformats-binary'
          - 'FasterXML/jackson-dataformats-text'
          - 'FasterXML/jackson-dataformat-xml'
          - 'FasterXML/jackson-datatypes-collections'
          - 'FasterXML/jackson-datatypes-misc'
          - 'FasterXML/jackson-module-kotlin'
          - 'FasterXML/jackson-module-scala'          

    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.token }}
          repository: ${{ matrix.repo }}
          event-type: jackson-databind-pushed
          # Could push information on what was built but not yet
          client-payload: '{"version": "N/A" }'
      - name: Delay between dispatches
        run: sleep 10s
        shell: bash
